name: "Continuous Integration"

on:
  pull_request:
  push:
    branches:
      - '[0-9]+.[0-9]+.x'
    tags:

jobs:
  ci:
    uses: laminas/workflow-continuous-integration/.github/workflows/continuous-integration.yml@1.x
  coverage:
    name: PHPUnit Coverage
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.6
      - uses: shivammathur/setup-php@2.30.4
        with:
          php-version: 8.1
          extensions: pcov
          coverage: pcov
          ini-values: pcov.enabled=1
      - uses: "ramsey/composer-install@3.0.0"
      - run: php ./vendor/bin/phpunit --coverage-clover=coverage.xml
        env:
          PRISMIC_REPO: ${{ secrets.PRISMIC_REPO }}
          PRISMIC_TOKEN: ${{ secrets.PRISMIC_TOKEN }}

      - uses: codecov/codecov-action@v4
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          fail_ci_if_error: false

  composer-require-checker:
    name: "Check for missing dependencies"
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@v4.1.6
      - uses: shivammathur/setup-php@2.30.4
        with:
          php-version: 8.1
      - uses: "ramsey/composer-install@3.0.0"
        with:
          dependency-versions: "highest"
      - run: composer global config bin-dir /usr/local/bin
      - run: composer global require -W maglnet/composer-require-checker
      - run: /usr/local/bin/composer-require-checker check
